version: "3.8"
services:
  lectures_db:
    container_name: lectures_db
    image: postgres:13
    restart: unless-stopped
    volumes:
      - lectures-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=lectures_admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=lectures
    networks:
      - knowit
  profile_db:
    container_name: profile_db
    image: postgres:13
    restart: unless-stopped
    volumes:
      - profile-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=profile_admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=profile
    networks:
      - knowit
  auth_db:
    container_name: auth_db
    image: postgres:13
    restart: unless-stopped
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=codexio_admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=auth
    networks:
      - knowit
  gateway_db:
    container_name: gateway-db
    image: redis
    restart: unless-stopped
    volumes:
      - gateway-db-data:/var/lib/etc/redis/data
    ports:
      - 6379:6379
    networks:
      - knowit
  zookeeper:
    container_name: zookeeper
    image:  wurstmeister/zookeeper
    ports:
      - 2181:2181
    environment:
      zk_id: 1
    networks:
      - knowit
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
    depends_on:
      - zookeeper
    networks:
      - knowit
  service-discovery:
    container_name: service-discovery
    build: ../service-discovery
    hostname: service-discovery
    environment:
      - ACTIVE_PROFILE=production
    restart: on-failure
    ports:
      - 8761:8761
    networks:
      - knowit
  auth:
    container_name: auth
    build: ../auth
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      - ACTIVE_PROFILE=production
      - DB_HOSTNAME=auth_db
      - DB_PORT=5432
      - DB_NAME=auth
      - DB_USER=codexio_admin
      - DB_PASS=root
      - EUREKA_HOSTNAME=service-discovery
      - KAFKA_HOST=kafka
      - JWT_SECRET=bezKoderSecretKey
      - REDIS_KEY=JwtKey
    networks:
      - knowit
    depends_on:
      - auth_db
      - service-discovery
      - kafka
  profile:
    container_name: profile
    build: ../profile
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      - ACTIVE_PROFILE=production
      - DB_HOSTNAME=profile_db
      - DB_PORT=5432
      - DB_NAME=profile
      - DB_USER=profile_admin
      - DB_PASS=root
      - EUREKA_HOSTNAME=service-discovery
      - KAFKA_HOST=kafka
    networks:
      - knowit
    depends_on:
      - profile_db
      - service-discovery
      - kafka
  gateway:
    container_name: gateway
    build: ../gateway
    restart: on-failure
    ports:
      - 8762:8762
    environment:
      - EUREKA_HOSTNAME=service-discovery
      - ACTIVE_PROFILE=production
      - JWT_SECRET=bezKoderSecretKey
      - REDIS_HOSTNAME=gateway_db
      - REDIS_PORT=6379
    networks:
      - knowit
    depends_on:
      - auth
      - service-discovery
      - profile
      - gateway_db
  file-manager:
    container_name: file-manager
    build: ../file-manager
    restart: on-failure
    ports:
      - 8084:8084
    environment:
      - ACTIVE_PROFILE=production
      - EUREKA_HOSTNAME=service-discovery
    networks:
      - knowit
    depends_on:
      - service-discovery
  web-client:
    container_name: web-client
    build:
      context: ../web-client
    restart: on-failure
    networks:
      - knowit
  proxy:
    container_name: proxy
    build:
      context: ../proxy
    restart: on-failure
    ports:
      - 80:80
    environment:
      - PORT=80
      - SERVER_NAME=localhost
      - WEB_CLIENT=web-client
      - BACKEND=gateway
      - BACKEND_PORT=8762
    depends_on:
      - web-client
    networks:
      - knowit
  lectures:
    container_name: lectures
    build: ../lectures
    restart: on-failure
    ports:
      - 8083:8083
    environment:
      - ACTIVE_PROFILE=production
      - DB_HOSTNAME=lectures_db
      - DB_PORT=5432
      - DB_NAME=lectures
      - DB_USER=lectures_admin
      - DB_PASS=root
      - EUREKA_HOSTNAME=service-discovery
      - KAFKA_HOST=kafka
    depends_on:
      - lectures_db
      - service-discovery
      - kafka
    networks:
      - knowit
volumes:
  auth-db-data:
  profile-db-data:
  gateway-db-data:
  lectures-db-data:
networks:
  knowit: