version: "3.8"
services:
  profile_db:
    container_name: profile_db
    image: postgres:13
    restart: unless-stopped
    volumes:
      - profile-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=profile_admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=profile
    networks:
      - knowit
  auth_db:
    container_name: auth_db
    image: postgres:13
    restart: unless-stopped
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=codexio_admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=auth
    networks:
      - knowit
  zookeeper:
    container_name: zookeeper
    image:  wurstmeister/zookeeper
    ports:
      - 2181:2181
    environment:
      zk_id: 1
    networks:
      - knowit
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
    depends_on:
      - zookeeper
    networks:
      - knowit
  service-discovery:
    container_name: service-discovery
    build: ../service-discovery
    hostname: service-discovery
    environment:
      - ACTIVE_PROFILE=production
    restart: on-failure
    ports:
      - 8761:8761
    networks:
      - knowit
  auth:
    container_name: auth
    build: ../auth
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      - ACTIVE_PROFILE=production
      - DB_HOSTNAME=auth_db
      - DB_PORT=5432
      - DB_NAME=auth
      - DB_USER=codexio_admin
      - DB_PASS=root
      - EUREKA_HOSTNAME=service-discovery
      - KAFKA_HOST=kafka
      - JWT_SECRET=bezKoderSecretKey
    networks:
      - knowit
    depends_on:
      - auth_db
      - service-discovery
      - kafka
  profile:
    container_name: profile
    build: ../profile
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      - ACTIVE_PROFILE=production
      - DB_HOSTNAME=profile_db
      - DB_PORT=5432
      - DB_NAME=profile
      - DB_USER=profile_admin
      - DB_PASS=root
      - EUREKA_HOSTNAME=service-discovery
      - KAFKA_HOST=kafka
    networks:
      - knowit
    depends_on:
      - profile_db
      - service-discovery
      - kafka
  gateway:
    container_name: gateway
    build: ../gateway
    restart: on-failure
    ports:
      - 8762:8762
    environment:
      - EUREKA_HOSTNAME=service-discovery
      - ACTIVE_PROFILE=production
      - JWT_SECRET=bezKoderSecretKey
    networks:
      - knowit
    depends_on:
      - auth
      - service-discovery
      - profile
volumes:
  auth-db-data:
  profile-db-data:
networks:
  knowit: